---
title: EDA, Thesis & Project wrap up
author: The A Team
date: '2022-12-02'
slug: []
categories: []
tags: []
description: ~
toc: yes
authors: []
series: []
lastmod: '2022-12-02T17:43:15-05:00'
featuredVideo: ~
featuredImage: ~
---

## Scope of Interactive Data Description 


|           For the final two blog posts I’m looking to see how you plan to wrap up the project. I’d like to hear about three things.
How are you continuing your exploratory data analysis? Remember all the ways we visualized the COVID data in just a couple days. Make sure you’ve done a thorough exploration for your project. Lots of ideas will be dead ends but keep looking and think about attaching more data.
What is your tentative thesis? Note that a thesis is not a hypothesis or a question. It should in some ways answer a question. (Eg. rather than, “What are the patterns of housing prices in Boston?“, something like, “Housing prices in Boston are rising rapidly, especially near T stations and along the water.“) The rest of the project should work to support that thesis. That doesn’t mean there won’t be any caveats or uncertainty, but you should try to accurately  provide details that provide evidence for your thesis.
How do you plan to polish your visualizations and tables? Think about titles, captions, annotations, highlights. Look into ggpubr for tools to improve your figures and look into some of the options for displaying tables using https://gallery.htmlwidgets.org/.

We Do NOT Need to answer every question this week, this is for blogpost 7 + 8

|           We are continuing our exploratory data analysis by making graphs that may or may not make the final cut. For example, we have recently made four graphs that explore which country loss certain commodity over 40% in a specific year and which commodity are loss the most through out history. Surprisingly, we found our that fruit juice – such as pineapple juice and orange juice loss the most as production throughout the production & retail process. However, we are unable to explain the reason behind this findings with our current data sets

|           After we found out US waste the most amount of food, we create a graph exploring US’s food waste throughout history. We found out that US’s food waste peaked at 2008, double the average amount of food waste across history. We suspect that there is a correlation between a countries financial performance and its ability to control food waste. Thus, we will be digging deeper into how GDP is connected with food waste. Does country with higher GDP tend to waste more food (as % of total production)? 

|           Our food waste & loss data set include detailed data for each country and each commodity across fifty year. We face difficulty when we attempt to find trend and tendency across dataset since there are too many dimensions. Therefore, we are exploring different options, such as using the country code to group country by regions (Such as North America, Asia..) or grouping commodity by the cdc code. 
