---
title: The Data
description: null
toc: yes
featuredVideo: null
featuredImage: 
draft: false
---

## Overview

|           With the world population recently surpassing the 8 billion threshold, and the increasing challenges of food security and scrutiny on the effects of agriculture on climate change, we wanted to further examine some of the relationships that factor into food waste and loss. 

|           The first step in our data collection process was to find data on Food Waste and Loss around the world, which we found via the Food and Agriculture Organization database. This dataset was curated by the United Nation in efforts to better identify food waste and loss in each country. In addition, the dataset provides information on food waste and loss based on commodities as well as stages in the supply chain. The dataset contains information on ____ countries and provides historical data of food waste and loss as a percentage dating back to the 1960's. (How it was collected) 

|           To supplement our analysis, we added variables that we considered to be relevant contributors to the overall food waste and loss. The first set of variables we introduced were Year, GDP, Percentage of GDP as Agriculture, Percentage of Land used for Agriculture, and Population by country. These datasets were extracted from the World Bank’s database, which actively collects general census data for most countries. To better match our primary Food Waste and Loss dataset, we have downloaded the datasets from the World Bank to date back to the 1960's as well. The next set we introduced is data on Food Production in tonnes. This data was curated, again, by the Food and Agriculture Organization of the United Nations, in an effort to study food waste and loss by country. The last variable that we added to our analysis was Region/Continent, which was sorted using Rstudio based on the country’s region. 

#### Links to data:
Food waste: [https://www.fao.org/platform-food-loss-waste/flw-data/en](https://www.fao.org/platform-food-loss-waste/flw-data/en)
Production:[https://www.fao.org/faostat/en/#data/QCL](https://www.fao.org/faostat/en/#data/QCL)
World Development Indicators: [https://databank.worldbank.org/reports.aspx?source=2&series=NY.GDP.MKTP.CD&country=#](https://databank.worldbank.org/reports.aspx?source=2&series=NY.GDP.MKTP.CD&country=#)


## Initial Cleaning Food Agriculture and Organization Data 


### Food Waste and Loss

|           The Food Waste and Loss dataset is the one that requires the least cleaning. As aforementioned, the dataset provides information about waste and loss based on stages in the supply chain. However, due to the data collection method utilized by the United Nation, this information is incomplete and inconsistent from country to country. Hence, because of the large amount of missing information, some columns will be removed from the original dataset for our research purposes. The data that will not be relevant to our analysis are: activity, commodities code (both given by name in addition to code), sample size (majority NA), treatment, references, cause_of_loss,method_data_collection,notes,loss_quantity, and url. 

|           We cleaned the dataset by piping the data using group_by, isolating the year, country, and commodity. This would allow us to use only what we need for this research and to size down the dataset. Later, piped this into a summarise() function to find the mean loss percentage, this would eliminate any duplicate commodities that were loss in the same year by the same country. This new cleaned dataset was stored in a new variable named fw1 (food waste 1).


### Food Production

|           The Food Production dataset; even though its file size is bigger; is relatively “cleaner” in comparison to the Food Waste and Loss dataset. The cleaning for this dataset that was done to remove Item Code (CPC), Item Code,Year Code, Flag, and Flag Description. Much like the treatment done to Food Waste and Loss, a new variable was made, fp1 (food production 1), That used the food_production dataset to be piped and group_by, the Item, Year, and Unit. 


## Initial Cleaning World Bank Data

|           The datasets extracted from the World Bank’s database are relatively “complete”. However, the four variables that we introduced using their database (GDP, Agriculture as Percentage of GDP, Percentage Agriculture Land, Population) share a common “issue”. Due to exogenous factors, some countries have a significant amount of missing values - mostly East European countries and small island nations. This is because they simply did not exist, and therefore, data was uncollectible. For example, much of the data for Eastern European countries are not available until mid-to-late 1990s as they existed within the Soviet Union prior to that. As such, we will have to treat the missing values as NA despite most available data dating back to the 1960s.

The cleaning for this portion of data was defining the “Year” columns as numeric rather than character as originally downloaded. The second part was to drop the irrelevant columns, including country code, series code, and series name. This can be seen in the chunk above/below:


## Packages Used to Clean Code:

|           Given that most of the cleaning required of the datasets were reorganization and redefining variables, a significant portion of the cleaning was used using dplyr. The remaining portion of the cleaning was done using base R functions. 


## Warnings:

|           For the cleaning of the World Bank data, due to the conversion from character to numeric, it prompts R to notify of warnings regarding the treatment of NAs. However, as we will continue to recognize the missing values (reasons discussed above), these warnings are ignored using the function supressWarnings(). 

## Data Variables: 

|           As stated before, this data set focused on food production and waste based on varying regions. As such, our data variables are quite easy to understand:

Area: This one is just the name of each designated region. Area can mean continent or country based on how precise we decide to be at the time. Eg.United States or Central America may both be viable names for Area. 
Item: This is the item in question that is being produced and measured, aka apples, almonds, etc.
Unit : 


